/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package finance02;

import entities.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.time.*;
import java.util.List;
import org.junit.Test;
import service.Impl.PurchaseServiceImpl;
import service.PurchaseService;

import static org.junit.Assert.*;
import org.junit.Before;

public class PurchaseTest {
    List<Purchase> purchases = new ArrayList<Purchase>();
    
    @Before
    public void setUp() {
        Purchase p1 = new Purchase(
            "36015828",
            LocalDate.of(2018, 2, 22),
            "120642",
            "180222710986153573",
            "710910010742065",
            "1300099C89",
            new BigDecimal(70000.00),
            "603302"
        );

        Purchase p2 = new Purchase(
            "36015828",
            LocalDate.of(2017, 10, 20),
            "132112",
            "171020710975085783",
            "710910010742065",
            "1300099C89",
            new BigDecimal(50000.00),
            "603302"
        );

        Purchase p3 = new Purchase(
            "36015828",
            LocalDate.of(2018, 2, 28),
            "125759",
            "180222710986153573",
            "710910010742065",
            "1300099C89",
            new BigDecimal(50000.00),
            "603302"
        );
        purchases.add(p1);
        purchases.add(p2);
        purchases.add(p3);
    }

    @Test 
    public void testSort() {

        PurchaseService pService = new PurchaseServiceImpl(purchases);
        
        pService.sort();

        List<Purchase> ps = pService.getPurchases();
        assertEquals(3, ps.size());
        assertEquals(LocalDate.of(2017, 10, 20), ps.get(0).getTranDate());
    }

    @Test 
    public void testIndex() {
        Redeem r = new Redeem(
            "36015828", 
            LocalDate.of(2018, 2, 27),
            "141759", 
            "180225710987050869", 
            "710910010742065",
            "1300099C89",
            new BigDecimal(50000.00),
            "603302",
            1,
            "171020710975085783"
        );
        PurchaseService pService = new PurchaseServiceImpl(purchases);
        int i = pService.index(r);
        assertEquals(1, i);
    }

    @Test
    public void testFindApplicationCodeIndex() {
        Redeem r = new Redeem(
            "36015828", 
            LocalDate.of(2018, 2, 27),
            "141759", 
            "180225710987050869", 
            "710910010742065",
            "1300099C89",
            new BigDecimal(80000.00),
            "603302",
            1,
            "171020710975085783"
        );
        PurchaseService pService = new PurchaseServiceImpl(purchases);
        int i = pService.findApplicationCodeIndex(r);
        assertEquals(0, i);
    }
}
