/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package finance02;
import entities.Purchase;
import org.junit.Test;
import service.Impl.PurchaseServiceImpl;
import service.PurchaseService;

public class PurchaseTest {
    @Test 
    public void testSort() {
        Purchase p1 = new Purchase();
        p1.setOrganCode("36015828");
        p1.setTranDate(2018, 2, 22, 0, 0, 0);
        p1.setTranTime("120642");
        p1.setApplicationCode("180222710986153573");
        p1.setTaCode("710910010742065");
        p1.setProdCode("1300099C89");
        p1.setTradeQuot(70000.00);
        p1.setTradeCode("603302");

        Purchase p2 = new Purchase();
        p2.setOrganCode("36015828");
        p2.setTranDate(2017, 10, 20, 0, 0, 0);
        p2.setTranTime("132112");
        p2.setApplicationCode("171020710975085783");
        p2.setTaCode("710910010742065");
        p2.setProdCode("1300099C89");
        p2.setTradeQuot(50000.00);
        p2.setTradeCode("603302");

        Purchase p3 = new Purchase();
        p3.setOrganCode("36015828");
        p3.setTranDate(2018, 2, 28, 0, 0, 0);
        p3.setTranTime("125759");
        p3.setApplicationCode("180228710987050869");
        p3.setTaCode("710910010742065");
        p3.setProdCode("1300099C89");
        p3.setTradeQuot(50000.00);
        p3.setTradeCode("603302");
        
        PurchaseService pService = new PurchaseServiceImpl();
        pService.sort();
        
    }
}
